package src.common;

public enum Commands {
    CMD_GET_WK, CMD_GET_WK_RESP,
    CMD_ERZEUGE_RECHNUNG, CMD_ERZEUGE_RECHNUNG_RESP,
    CMD_GIB_EREIGNISLISTE, CMD_GIB_EREIGNISLISTE_RESP,
    CMD_GIB_ALLE_ARTIKEL, CMD_GIB_ALLE_ARTIKEL_RESP,
    CMD_CHECK_LOGIN, CMD_CHECK_LOGIN_RESP,
    CHECK_PASSWORT, CHECK_PASSWORT_RESP,
    CMD_CHECK_PACKUNGSGROESSE, CMD_CHECK_PACKUNGSGROESSE_RESP,
    CMD_HOLE_ARTIKEL, CMD_HOLE_ARTIKEL_RESP,
    CMD_ARTIKEL_ZURUECK, CMD_ARTIKEL_ZURUECK_RESP,
    CMD_ARTIKEL_BESTAND_VERRINGERN, CMD_ARTIKEL_BESTAND_VERRINGERN_RESP,
    CMD_IST_ARTIKEL_IM_WARENKORB, CMD_IST_ARTIKEL_IM_WARENKORB_RESP,
    CMD_CHECK_ANZAHL_DES_ARTIKELS, CMD_CHECK_ANZAHL_DES_ARTIKELS_RESP,
    CMD_KUNDE_ANLEGEN, CMD_KUNDE_ANLEGEN_RESP,
    CMD_ARTIKEL_ANLEGEN, CMD_ARTIKEL_ANLEGEN_RESP,
    CMD_EREIGNIS_BESTAND_ERHOEHT, CMD_EREIGNIS_BESTAND_ERHOEHT_RESP,
    CMD_MITARBEITER_ANLEGEN, CMD_MITARBEITER_ANLEGEN_RESP,
    CMD_SCHREIBE_ARTIKEL_DATEN, CMD_SCHREIBE_ARTIKEL_DATEN_RESP,
    CMD_SCHREIBE_MITARBEITER_DATEN, CMD_SCHREIBE_MITARBEITER_DATEN_RESP,
    CMD_SCHREIBE_KUNDEN_DATEN, CMD_SCHREIBE_KUNDEN_DATEN_RESP,
    CMD_SCHREIBE_EREIGNIS_DATEN, CMD_SCHREIBE_EREIGNIS_DATEN_RESP,
    CMD_SUCHE_ARTIKEL, CMD_SUCHE_ARTIKEL_RESP,
    CMD_SUCHE_EREIGNIS, CMD_SUCHE_EREIGNIS_RESP,
    CMD_SUCHE_NACH_TITEL, CMD_SUCHE_NACH_TITEL_RESP,
    CMD_SUCHE_NACH_EREIGNIS, CMD_SUCHE_NACH_EREIGNIS_RESP
}
